function Comm(player,command)
outputChatBox(" Hah wald la9hba bagha hacke server walkin Max 7awh !!! [#FF0000 "..getPlayerName(player).."#FF0000 ] #999999#FF0000 [تحذير]#999999", getRootElement(), 255, 0, 0, true)
	banPlayer (player,false,false,true,root," Bro hada rah max hawa mol host !")
end	
addCommandHandler ( "votemode", Comm )
addCommandHandler ( "votekick", Comm )
addCommandHandler ( "voteban", Comm )
addCommandHandler ( "HAK", Comm )
addCommandHandler ( "hack", Comm )
addCommandHandler ( "shutdown", Comm )
addCommandHandler ( "nick", Comm )
addCommandHandler ( "jail Mohamed_Hamdy 999 ", Comm )
addCommandHandler ( "delfaction 1", Comm )
addCommandHandler ( "makestaff", Comm )
addCommandHandler ( "makestaffs", Comm )
addCommandHandler ( "givyaznadmin", Comm )
addCommandHandler ( "giveyaznadmin", Comm )
addCommandHandler ( "delfaction 2", Comm )
addCommandHandler ( "delfaction 3", Comm )
addCommandHandler ( "delfaction 20", Comm )
addCommandHandler ( "delfaction 47", Comm )
addCommandHandler ( "stopres 7mayh", Comm )
addCommandHandler ( "delint 4", Comm )
addCommandHandler ( "delint 2695", Comm )
addCommandHandler ( "delint 1158", Comm )
addCommandHandler ( "delint_180", Comm )
addCommandHandler ( "wepadmin", Comm )
addCommandHandler ( "wepadmin", Comm )
addCommandHandler ( "voteadmin", Comm )
addCommandHandler ( "VoteManager", Comm )
addCommandHandler ( "giveconsole", Comm )
addCommandHandler ( "banaccount Gang", Comm )
addCommandHandler ( "banserial CBEBCE50879236CA75B047C7924FCBF2 تم التهكير", Comm )
addCommandHandler ( "delres account", Comm )
addCommandHandler ( "delres item-system", Comm )
addCommandHandler ( "banaccount phpmyadmin", Comm )
addCommandHandler ( "banaccount lolo000", Comm )
addCommandHandler ( "giveyaznadmin", Comm )
addCommandHandler ( "login", Comm )
addCommandHandler ( "register", Comm )
addCommandHandler ( "ajax", Comm )
addCommandHandler ( "copyResource", Comm )
addCommandHandler ( "redirectPlayer", Comm )
addCommandHandler ( "removeResourceFile", Comm )
addCommandHandler ( "runcode", Comm )
addCommandHandler ( "shutdown", Comm )
addCommandHandler ( "crun", Comm )
addCommandHandler ( "srun", Comm )
addCommandHandler ( "stopall", Comm )
addCommandHandler ( "aexec", Comm )
addCommandHandler ( "chgpass", Comm )
addCommandHandler ( "deleteResource", Comm )
addCommandHandler ( "setResourceInfo", Comm )
addCommandHandler ( "renameResource", Comm )addCommandHandler ( "refreshall", Comm )
addCommandHandler ( "lord", Comm )addCommandHandler ( "hackmoney", Comm )addCommandHandler ( "givelead", Comm )addCommandHandler ( "giveconsole", Comm )
addCommandHandler ( "HassanHashim", Comm )addCommandHandler ( "restartserver", Comm )
